all:
  children:
    dns:
      hosts:
        dns1.lan:
        dns2.lan:
    lxc_hosts:
      hosts:
        marshhouse.lan:
        oiwas.lan:
    lxc_containers:
      hosts:
        dns1.lan:
        dns2.lan:
        dash.lan:
        mqtt.lan:
        rip.lan:
        nodered.lan:
        prometheus.lan:
        hisako.lan:
        ddns.lan:
        zigbee.lan:
        hassle.lan:
    pis:
      hosts:
        rpizw2.lan:
        rpizw4.lan:
        rpizw5.lan:
        rpizw6.lan:
  hosts:
    # rpizw1.lan:
    # rpizw2.lan:
    #  admin_user: pi
    # rpizw3.lan:
    # rpizw4.lan:
    #  admin_user: pi
    # rpizw5.lan:
    # rpizw6.lan:
  
    cliff.lan:
