- hosts: all
  become: yes

  vars_prompt:
  - name: download_url
    prompt: Node Exporter download URL
    private: no

  tasks:
  - name: Create system group
    group:
      name: prometheus
      system: yes
  - name: Create system user
    user:
      name: prometheus
      group: prometheus
      system: yes
      shell: /sbin/nologin
      home: /var/lib/prometheus
  # - name: Download Node Exporter archive
  #   get_url:
  #     url: "{{ download_url }}"
  #     dest: .
  #   register: downloaded_archive
  # - name: Unpack Node Exporter archive
  #   unarchive:
  #     src: "{{ downloaded_archive.dest }}"
  #     dest: .
  #     remote_src: yes
  #     extra_opts:
  #     - --strip-components=1
  - name: Download and unpack Node Exporter archive
    unarchive:
      dest: .
      src: "{{ download_url }}"
      remote_src: yes
      extra_opts:
      # REALLY FUCKING IMPORTANT YOU DO NOT PUT QUOTE MARKS HERE, AND DO --option=value INSTEAD OF --option value
      - --strip-components=1
  - name: Copy binaries to system
    copy:
      src: node_exporter
      dest: /usr/local/bin/
      mode: 0775
      remote_src: yes
  - name: Copy systemd service file
    copy:
      src: node_exporter.service
      dest: /etc/systemd/system/
  - name: Reload systemd daemon and start Node Exporter
    systemd:
      name: node_exporter
      state: started
      enabled: yes
      daemon_reload: yes
